### ISSUE TITLE
Gentle web app not loading

### ISSUE THREAD

**Issue by parkerac** [dhiego22/gentle#3]
Hi, I am excited to try this new software. When I click on the link to the web app version it says "Error running app. If this keeps happening, please contact support." Can you help me?

**Comment by dhiego22** [comment]
Thank you for sharing it. The problem was fixed. GENTLE is running and
ready to use again. Please, feel free to share any ideas or issues with us.
Best regards,
Dhiego

Em seg., 6 de fev. de 2023 às 14:38, parkerac ***@***.***>
escreveu:

**Comment by parkerac** [comment]
Great! Thank you so much. I am able to access it now.
